<?php

namespace Modules\Employee\Database\Seeders\EmployeeCourse;

use Illuminate\Database\Seeder;
use Modules\Employee\Models\EmployeeCourse;

class EmployeeCourseSeeder extends Seeder
{
    public function run(): void
    {
        $employee_courses = [
            [
                'employee_id' => 1,
                'course_name' => 'Sample course_name 1',
                'course_type' => 'Sample course_type 1',
                'program_type' => 'Sample program_type 1',
                'sponsored' => 'Sample sponsored 1',
                'start_date' => '2009-10-08',
                'end_date' => '2020-10-08',
                'course_value' => 23.25,
                'trainer' => 'Sample trainer 1',
                'training_entity' => 'Sample training_entity 1',
                'training_location' => 'Sample training_location 1',
                'country_id' => 1,
                'city_id' => 3,
                'location' => 'Sample location 1',
                'issuer' => 'Sample issuer 1',
                'certificate_number' => 'Sample certificate_number 1',
                'certificate_end_date' => '2015-10-08',
                'certificate_issue_date' => '2022-10-08',
                'grade' => 'Sample grade 1',
                'hours_count' => 84,
                'notes' => 'Sample notes 1',
            ],
            [
                'employee_id' => 1,
                'course_name' => 'Sample course_name 2',
                'course_type' => 'Sample course_type 2',
                'program_type' => 'Sample program_type 2',
                'sponsored' => 'Sample sponsored 2',
                'start_date' => '2011-10-08',
                'end_date' => '2017-10-08',
                'course_value' => 52.57,
                'trainer' => 'Sample trainer 2',
                'training_entity' => 'Sample training_entity 2',
                'training_location' => 'Sample training_location 2',
                'country_id' => 1,
                'city_id' => 2,
                'location' => 'Sample location 2',
                'issuer' => 'Sample issuer 2',
                'certificate_number' => 'Sample certificate_number 2',
                'certificate_end_date' => '2017-10-08',
                'certificate_issue_date' => '2021-10-08',
                'grade' => 'Sample grade 2',
                'hours_count' => 532,
                'notes' => 'Sample notes 2',
            ],
            [
                'employee_id' => 3,
                'course_name' => 'Sample course_name 3',
                'course_type' => 'Sample course_type 3',
                'program_type' => 'Sample program_type 3',
                'sponsored' => 'Sample sponsored 3',
                'start_date' => '2022-10-08',
                'end_date' => '2010-10-08',
                'course_value' => 73.16,
                'trainer' => 'Sample trainer 3',
                'training_entity' => 'Sample training_entity 3',
                'training_location' => 'Sample training_location 3',
                'country_id' => 2,
                'city_id' => 1,
                'location' => 'Sample location 3',
                'issuer' => 'Sample issuer 3',
                'certificate_number' => 'Sample certificate_number 3',
                'certificate_end_date' => '2008-10-08',
                'certificate_issue_date' => '2020-10-08',
                'grade' => 'Sample grade 3',
                'hours_count' => 513,
                'notes' => 'Sample notes 3',
            ],
            [
                'employee_id' => 2,
                'course_name' => 'Sample course_name 4',
                'course_type' => 'Sample course_type 4',
                'program_type' => 'Sample program_type 4',
                'sponsored' => 'Sample sponsored 4',
                'start_date' => '2005-10-08',
                'end_date' => '2024-10-08',
                'course_value' => 2.10,
                'trainer' => 'Sample trainer 4',
                'training_entity' => 'Sample training_entity 4',
                'training_location' => 'Sample training_location 4',
                'country_id' => 1,
                'city_id' => 2,
                'location' => 'Sample location 4',
                'issuer' => 'Sample issuer 4',
                'certificate_number' => 'Sample certificate_number 4',
                'certificate_end_date' => '2006-10-08',
                'certificate_issue_date' => '2019-10-08',
                'grade' => 'Sample grade 4',
                'hours_count' => 254,
                'notes' => 'Sample notes 4',
            ],
            [
                'employee_id' => 3,
                'course_name' => 'Sample course_name 5',
                'course_type' => 'Sample course_type 5',
                'program_type' => 'Sample program_type 5',
                'sponsored' => 'Sample sponsored 5',
                'start_date' => '2021-10-08',
                'end_date' => '2014-10-08',
                'course_value' => 22.19,
                'trainer' => 'Sample trainer 5',
                'training_entity' => 'Sample training_entity 5',
                'training_location' => 'Sample training_location 5',
                'country_id' => 1,
                'city_id' => 2,
                'location' => 'Sample location 5',
                'issuer' => 'Sample issuer 5',
                'certificate_number' => 'Sample certificate_number 5',
                'certificate_end_date' => '2022-10-08',
                'certificate_issue_date' => '2011-10-08',
                'grade' => 'Sample grade 5',
                'hours_count' => 994,
                'notes' => 'Sample notes 5',
            ],
        ];

        foreach ($employee_courses as $data) {
            EmployeeCourse::firstOrCreate($data);
        }
    }
}
